# Generated by Django 5.2.15 on 2026-06-25 23:43

import apps.pedidos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legado_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('designer', models.CharField(blank=True, max_length=120)),
                ('tema', models.CharField(blank=True, max_length=180)),
                ('descricao_legada', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(blank=True, null=True)),
                ('data_pedido', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago_legado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto_ajuste', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pagamento_legada', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartao'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('OUTRO', 'Outro'), ('NAO_INFORMADO', 'Nao informado')], default='NAO_INFORMADO', max_length=32)),
                ('status', models.CharField(choices=[('EM_PRODUCAO', 'Em producao'), ('AGUARDANDO_ARTE', 'Aguardando arte'), ('PRONTO', 'Pedido pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='EM_PRODUCAO', max_length=32)),
                ('origem', models.CharField(choices=[('BALCAO', 'Balcao'), ('WHATSAPP', 'WhatsApp'), ('IA', 'IA'), ('LEGADO', 'Legado'), ('OUTRO', 'Outro')], default='LEGADO', max_length=24)),
                ('pdf_gerado_por', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartao'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('OUTRO', 'Outro'), ('NAO_INFORMADO', 'Nao informado')], default='NAO_INFORMADO', max_length=32)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='CONFIRMADO', max_length=24)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('EM_PRODUCAO', 'Em producao'), ('AGUARDANDO_ARTE', 'Aguardando arte'), ('PRONTO', 'Pedido pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=32)),
                ('status_novo', models.CharField(choices=[('EM_PRODUCAO', 'Em producao'), ('AGUARDANDO_ARTE', 'Aguardando arte'), ('PRONTO', 'Pedido pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=32)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArtePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to=apps.pedidos.models.arte_upload_to)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('legado_base64_hash', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artes', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['pedido_id', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_unitario_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalogo.produtoservico')),
            ],
            options={
                'ordering': ['pedido_id', 'ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'data_entrega'], name='pedidos_ped_status_95e044_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['data_pedido'], name='pedidos_ped_data_pe_67be7b_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['designer'], name='pedidos_ped_designe_d3d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['origem'], name='pedidos_ped_origem_2b6be0_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentopedido',
            index=models.Index(fields=['status', 'data_pagamento'], name='pedidos_pag_status_fdd33f_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentopedido',
            index=models.Index(fields=['forma'], name='pedidos_pag_forma_0f67cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoitem',
            index=models.Index(fields=['nome'], name='pedidos_ped_nome_f74711_idx'),
        ),
    ]
