# Generated by Django 5.2.15 on 2026-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario_cadastro',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
