# Generated by Django 5.2.15 on 2026-06-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_perfilempresa_operadorgestor_atualizado_em_and_more'),
        ('pedidos', '0002_pedido_usuario_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='categoria_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalogo.categoriaservico'),
        ),
    ]
