# Generated by Django 5.2.15 on 2026-06-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0003_pedidoitem_categoria_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicostatuspedido',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_ARTE', 'Aguardando arte'), ('ARTE_EM_PREPARO', 'Arte em preparo'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('LIBERADO_PRODUCAO', 'Liberado para producao'), ('EM_PRODUCAO', 'Em producao'), ('PRONTO', 'Pronto para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicostatuspedido',
            name='status_novo',
            field=models.CharField(choices=[('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_ARTE', 'Aguardando arte'), ('ARTE_EM_PREPARO', 'Arte em preparo'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('LIBERADO_PRODUCAO', 'Liberado para producao'), ('EM_PRODUCAO', 'Em producao'), ('PRONTO', 'Pronto para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_ARTE', 'Aguardando arte'), ('ARTE_EM_PREPARO', 'Arte em preparo'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao'), ('LIBERADO_PRODUCAO', 'Liberado para producao'), ('EM_PRODUCAO', 'Em producao'), ('PRONTO', 'Pronto para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_ARTE', max_length=32),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['prioridade', 'data_entrega'], name='pedidos_ped_priorid_c1b09f_idx'),
        ),
    ]
