# Generated by Django 5.2.15 on 2026-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='caminho_arquivo_corel',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
