# Generated by Django 5.2.15 on 2026-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='canal_atendimento',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('INDICACAO', 'Indicacao'), ('OUTRO', 'Outro')], default='PRESENCIAL', max_length=16),
        ),
    ]
