# Generated by Django 5.2.16 on 2026-08-01 23:09

from django.db import migrations, models
from django.db.models import Sum


def preencher_estados_independentes(apps, schema_editor):
    Pedido = apps.get_model("pedidos", "Pedido")
    for pedido in Pedido.objects.all().iterator():
        estado_comercial = "CONFIRMADO"
        estado_entrega = "PENDENTE"
        if pedido.status == "CANCELADO":
            estado_comercial = "CANCELADO"
        elif pedido.status == "PRONTO":
            estado_entrega = "PRONTO"
        elif pedido.status == "ENTREGUE":
            estado_entrega = "ENTREGUE"
            pago = pedido.pagamentos.filter(status="CONFIRMADO").aggregate(total=Sum("valor"))[
                "total"
            ] or 0
            pago = max(pago, pedido.valor_pago_legado or 0)
            if pago >= pedido.valor_total:
                estado_comercial = "CONCLUIDO"
        Pedido.objects.filter(pk=pedido.pk).update(
            estado_comercial=estado_comercial,
            estado_entrega=estado_entrega,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_historicostatuspedido_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_comercial',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluido')], default='CONFIRMADO', max_length=16),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRONTO', 'Pronto para entrega'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=16),
        ),
        migrations.RunPython(preencher_estados_independentes, migrations.RunPython.noop),
    ]
