# Generated by Django 5.2.16 on 2026-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_estado_comercial_pedido_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_visivel_offline',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estacao_origem_offline',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='identificador_offline',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origem_offline',
            field=models.BooleanField(default=False),
        ),
    ]
