# Generated by Django 5.2.16 on 2026-08-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
        ('pedidos', '0010_pedido_codigo_visivel_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artepedido',
            name='conteudo_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='artepedido',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artes_referencia_adicionadas', to='catalogo.operadorgestor'),
        ),
        migrations.AddField(
            model_name='artepedido',
            name='desvinculado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artepedido',
            name='desvinculado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artes_referencia_desvinculadas', to='catalogo.operadorgestor'),
        ),
        migrations.AlterField(
            model_name='artepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artes', to='pedidos.pedido'),
        ),
    ]
