# Generated by Django 5.2.16 on 2026-08-01 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0015_operadorgestor_canal_atendimento_padrao'),
        ('pedidos', '0009_pedido_estado_comercial_pedido_estado_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloFluxo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=160)),
                ('versao', models.PositiveIntegerField()),
                ('definicao_etapas', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('codigo', 'versao'), name='operacao_fluxo_versao_unica')],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('objetivo', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('modelo_codigo_snapshot', models.CharField(max_length=80)),
                ('modelo_versao_snapshot', models.PositiveIntegerField()),
                ('estado_operacional', models.CharField(choices=[('NAO_INICIADO', 'Nao iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADO', 'Bloqueado'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado'), ('INVIABILIZADO', 'Inviabilizado'), ('ABANDONADO', 'Abandonado'), ('SUBSTITUIDO', 'Substituido')], default='NAO_INICIADO', max_length=24)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo_fluxo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacao.modelofluxo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField()),
                ('obrigatoria', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('NAO_INICIADA', 'Nao iniciada'), ('AGUARDANDO_CONDICAO', 'Aguardando condicao externa'), ('PRONTA', 'Pronta para execucao'), ('EM_ANDAMENTO', 'Em andamento'), ('BLOQUEADA', 'Bloqueada'), ('CONCLUIDA', 'Concluida'), ('DISPENSADA', 'Dispensada'), ('CANCELADA', 'Cancelada'), ('REABERTA', 'Reaberta')], max_length=24)),
                ('motivo_bloqueio', models.TextField(blank=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_concluidas', to='catalogo.operadorgestor')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_responsaveis', to='catalogo.operadorgestor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='operacao.processo')),
            ],
            options={
                'ordering': ['processo_id', 'ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(fields=('pedido', 'tipo'), name='operacao_processo_tipo_pedido_unico'),
        ),
        migrations.AddConstraint(
            model_name='etapaprocesso',
            constraint=models.UniqueConstraint(fields=('processo', 'chave'), name='operacao_etapa_chave_unica'),
        ),
    ]
