# Generated by Django 5.2.16 on 2026-08-02 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('objetivo', models.TextField()),
                ('criterio_conclusao', models.TextField()),
                ('resultado_esperado', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('VOLUNTARIA', 'Voluntária'), ('ADMINISTRATIVA', 'Administrativa'), ('IA_ACEITA', 'Sugestão da IA aceita')], max_length=24)),
                ('estado', models.CharField(choices=[('PROPOSTA', 'Proposta'), ('AGUARDANDO_ACEITE', 'Aguardando aceite'), ('PLANEJADA', 'Planejada'), ('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('BLOQUEADA', 'Bloqueada'), ('EM_REVISAO', 'Em revisão'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('ARQUIVADA', 'Arquivada')], max_length=24)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missoes_criadas', to='catalogo.operadorgestor')),
                ('responsavel_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missoes_responsaveis', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-atualizada_em', '-criada_em'],
            },
        ),
    ]
