# Generated by Django 5.2.16 on 2026-08-02 14:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
        ('missoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='ajuda_necessaria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='concluida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missoes_concluidas', to='catalogo.operadorgestor'),
        ),
        migrations.AddField(
            model_name='missao',
            name='dependencia_bloqueio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='impacto_bloqueio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='motivo_bloqueio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='pausada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='pendencias_remanescentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='resultado_alcancado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missao',
            name='tempo_total_pausa',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='missao',
            name='urgencia_bloqueio',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
