# Generated by Django 5.2.16 on 2026-08-02 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
        ('missoes', '0002_missao_ajuda_necessaria_missao_concluida_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='autoridade_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missoes_sob_autoridade', to='catalogo.operadorgestor'),
        ),
        migrations.AddField(
            model_name='missao',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL_VOLUNTARIA', 'Individual voluntária'), ('INDIVIDUAL_ATRIBUIDA', 'Individual atribuída'), ('COLETIVA_ESPONTANEA', 'Coletiva espontânea'), ('COLETIVA_ATRIBUIDA', 'Coletiva atribuída')], default='INDIVIDUAL_VOLUNTARIA', max_length=32),
        ),
        migrations.CreateModel(
            name='ParticipacaoMissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('LIDER', 'Líder'), ('PARTICIPANTE', 'Participante'), ('OBSERVADOR', 'Observador autorizado'), ('APROVADOR', 'Aprovador')], max_length=24)),
                ('estado_participacao', models.CharField(choices=[('CONVIDADO', 'Convidado'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('SAIU', 'Saiu voluntariamente'), ('REMOVIDO', 'Removido pela autoridade'), ('ATRIBUIDO', 'Atribuído formalmente')], max_length=24)),
                ('convidado_em', models.DateTimeField(blank=True, null=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('manifestacao_tipo', models.CharField(blank=True, choices=[('MAIS_INFORMACOES', 'Pediu mais informações'), ('AJUSTE_PARTICIPACAO', 'Sugeriu ajuste de participação')], max_length=32)),
                ('manifestacao_texto', models.TextField(blank=True)),
                ('motivo_saida', models.TextField(blank=True)),
                ('impacto_saida_confirmado', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('convidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_missao_emitidos', to='catalogo.operadorgestor')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='missoes.missao')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_missao', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['criada_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('encerrado_em__isnull', True)), fields=('missao', 'operador'), name='missoes_participacao_corrente_unica')],
            },
        ),
    ]
