# Generated by Django 5.2.16 on 2026-08-02 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
        ('missoes', '0003_missao_autoridade_responsavel_missao_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChatMissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_chat_missao', to='catalogo.operadorgestor')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_chat', to='missoes.missao')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaMissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_missao_autor', to='catalogo.operadorgestor')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='missoes.missao')),
            ],
            options={
                'ordering': ['-atualizada_em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaMissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=24)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_missao_concluidas', to='catalogo.operadorgestor')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='missoes.missao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_missao_responsaveis', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['ordem', 'criada_em'],
            },
        ),
    ]
