# Generated by Django 5.2.16 on 2026-09-02 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
        ('missoes', '0004_mensagemchatmissao_notamissao_tarefamissao'),
        ('pedidos', '0011_artepedido_conteudo_sha256_artepedido_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missao',
            name='origem',
            field=models.CharField(choices=[('VOLUNTARIA', 'Voluntária'), ('ADMINISTRATIVA', 'Administrativa'), ('SUGESTAO_ACEITA', 'Sugestão do sistema aceita'), ('IA_ACEITA', 'Sugestão da IA aceita')], max_length=24),
        ),
        migrations.CreateModel(
            name='ReferenciaPedidoMissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_pedido', to='missoes.missao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_missoes', to='pedidos.pedido')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_pedido_missao_registradas', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['pedido_id'],
                'constraints': [models.UniqueConstraint(fields=('missao', 'pedido'), name='missoes_missao_pedido_unico')],
            },
        ),
    ]
