# Generated by Django 5.2.16 on 2026-08-18 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-atualizada_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensagemCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('USUARIO', 'Usuário'), ('MHEIBOS', 'Mheibos'), ('SISTEMA', 'Sistema')], max_length=16)),
                ('texto', models.TextField()),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='cognicao.conversacognitiva')),
            ],
            options={
                'ordering': ['criada_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TarefaCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=16)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='cognicao.conversacognitiva')),
                ('mensagem_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='cognicao.mensagemcognitiva')),
            ],
            options={
                'ordering': ['criada_em', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacognitiva',
            index=models.Index(fields=['operador', 'ativa'], name='cognicao_co_operado_57bccf_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefacognitiva',
            index=models.Index(fields=['estado', 'criada_em'], name='cognicao_ta_estado_ba265d_idx'),
        ),
    ]
