# Generated by Django 5.2.16 on 2026-08-18 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
        ('cognicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacognitiva',
            name='origem',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('WHATSAPP', 'WhatsApp')], default='GESTOR', max_length=24),
        ),
        migrations.AddField(
            model_name='conversacognitiva',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conversacognitiva',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.operadorgestor'),
        ),
        migrations.AlterField(
            model_name='mensagemcognitiva',
            name='papel',
            field=models.CharField(choices=[('USUARIO', 'Usuário'), ('MHEIBOS', 'Mheibos'), ('SISTEMA', 'Sistema'), ('WHATSAPP', 'WhatsApp')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='conversacognitiva',
            index=models.Index(fields=['origem', 'referencia_externa'], name='cognicao_co_origem_6e2642_idx'),
        ),
    ]
