# Generated by Django 5.2.16 on 2026-08-31 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
        ('cognicao', '0003_alerta_cognitiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertacognitiva',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alertacognitiva',
            name='resolvida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertacognitiva',
            name='resolvida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_cognitivos_resolvidos', to='catalogo.operadorgestor'),
        ),
        migrations.AddField(
            model_name='alertacognitiva',
            name='severidade',
            field=models.CharField(default='NORMAL', max_length=16),
        ),
        migrations.AddField(
            model_name='alertacognitiva',
            name='ultima_avaliacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='custo_estimado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='duracao_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='modelo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='thinking_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='tokens_input',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='tokens_output',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefacognitiva',
            name='workload',
            field=models.CharField(default='assistant', max_length=32),
        ),
        migrations.CreateModel(
            name='EventoAtividadeCognitiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=48)),
                ('alvo_tipo', models.CharField(blank=True, max_length=48)),
                ('alvo_id', models.CharField(blank=True, max_length=80)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('ocorreu_em', models.DateTimeField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-ocorreu_em', '-id'],
                'indexes': [models.Index(fields=['operador', 'ocorreu_em'], name='cognicao_ev_operado_8d23ab_idx'), models.Index(fields=['operador', 'alvo_tipo', 'alvo_id', 'ocorreu_em'], name='cognicao_ev_operado_3d9a44_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntervencaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(default='gemini', max_length=32)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('estrategia', models.CharField(default='intervention', max_length=48)),
                ('mensagem', models.TextField()),
                ('acoes_disponiveis', models.JSONField(blank=True, default=list)),
                ('contexto_hash', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('GERADA', 'Gerada'), ('EXIBIDA', 'Exibida'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('IGNORADA', 'Ignorada'), ('RESOLVIDA', 'Resolvida')], default='GERADA', max_length=16)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('exibida_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_usuario', models.CharField(blank=True, max_length=24)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('tokens_input', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveIntegerField(blank=True, null=True)),
                ('thinking_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('alerta_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intervencoes', to='cognicao.alertacognitiva')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.operadorgestor')),
                ('tarefa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intervencao', to='cognicao.tarefacognitiva')),
            ],
            options={
                'ordering': ['-criada_em', '-id'],
                'indexes': [models.Index(fields=['operador', 'estado', 'criada_em'], name='cognicao_in_operado_12dd1e_idx'), models.Index(fields=['contexto_hash'], name='cognicao_in_context_4bfc7a_idx')],
            },
        ),
    ]
