# Generated by Django 5.2.15 on 2026-06-29 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaAprendizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=24)),
                ('instancia', models.CharField(blank=True, max_length=80)),
                ('contato_id', models.CharField(max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=32)),
                ('nome_contato', models.CharField(blank=True, max_length=160)),
                ('primeira_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('total_mensagens', models.PositiveIntegerField(default=0)),
                ('total_cliente', models.PositiveIntegerField(default=0)),
                ('total_empresa', models.PositiveIntegerField(default=0)),
                ('tem_lead', models.BooleanField(default=False)),
                ('tem_reclamacao', models.BooleanField(default=False)),
                ('tem_sinal_pedido', models.BooleanField(default=False)),
                ('util_para_treinamento', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversa de aprendizado',
                'verbose_name_plural': 'Conversas de aprendizado',
                'indexes': [models.Index(fields=['origem', 'instancia'], name='aprendizado_origem_121f7f_idx'), models.Index(fields=['ultima_mensagem_em'], name='aprendizado_ultima__74682f_idx'), models.Index(fields=['util_para_treinamento'], name='aprendizado_util_pa_22449b_idx'), models.Index(fields=['tem_lead', 'tem_reclamacao'], name='aprendizado_tem_lea_0c0a7c_idx')],
                'unique_together': {('origem', 'instancia', 'contato_id')},
            },
        ),
        migrations.CreateModel(
            name='AmostraTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONVERSA', 'Conversa'), ('LEAD', 'Lead'), ('RECLAMACAO', 'Reclamacao'), ('PEDIDO', 'Pedido')], max_length=24)),
                ('conteudo', models.JSONField(default=dict)),
                ('qualidade', models.PositiveSmallIntegerField(default=1)),
                ('pronta', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='aprendizado.conversaaprendizado')),
            ],
            options={
                'verbose_name': 'Amostra de treinamento',
                'verbose_name_plural': 'Amostras de treinamento',
                'indexes': [models.Index(fields=['tipo', 'pronta'], name='aprendizado_tipo_e800cf_idx')],
                'unique_together': {('conversa', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='MensagemAprendizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_id', models.CharField(max_length=160)),
                ('direcao', models.CharField(choices=[('CLIENTE', 'Cliente'), ('EMPRESA', 'Empresa'), ('SISTEMA', 'Sistema')], max_length=16)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('texto', models.TextField(blank=True)),
                ('enviada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='aprendizado.conversaaprendizado')),
            ],
            options={
                'verbose_name': 'Mensagem de aprendizado',
                'verbose_name_plural': 'Mensagens de aprendizado',
                'ordering': ['enviada_em', 'id'],
                'indexes': [models.Index(fields=['direcao', 'tipo'], name='aprendizado_direcao_aac38f_idx'), models.Index(fields=['enviada_em'], name='aprendizado_enviada_543128_idx')],
                'unique_together': {('conversa', 'mensagem_id')},
            },
        ),
    ]
