# Generated by Django 5.2.16 on 2026-08-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizado', '0001_initial'),
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('camada', models.CharField(choices=[('UNIVERSAL', 'Universal do Mheibos'), ('INSTITUCIONAL', 'Institucional da empresa'), ('OPERACIONAL', 'Operacional'), ('MEMORIA_LONGA', 'Memória de longo prazo'), ('MEMORIA_CURTA', 'Memória de curto prazo')], max_length=24)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=16)),
                ('fonte', models.CharField(max_length=240)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('valido_de', models.DateTimeField(blank=True, null=True)),
                ('valido_ate', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
                'indexes': [models.Index(fields=['camada', 'estado'], name='aprendizado_camada_a12a97_idx'), models.Index(fields=['fonte'], name='aprendizado_fonte_cd0967_idx')],
            },
        ),
    ]
