# Generated by Django 5.2.16 on 2026-08-10 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendizado', '0002_conhecimento'),
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=160)),
                ('conteudo', models.JSONField(default=dict)),
                ('curta', models.BooleanField(default=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('fonte', models.CharField(default='sessao_mheibos', max_length=240)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorias_operacionais', to='catalogo.operadorgestor')),
            ],
            options={
                'indexes': [models.Index(fields=['operador', 'curta'], name='aprendizado_operado_4bb0c6_idx'), models.Index(fields=['expira_em'], name='aprendizado_expira__ebea13_idx')],
                'constraints': [models.UniqueConstraint(fields=('operador', 'chave'), name='aprendizado_memoria_operador_chave_unica')],
            },
        ),
    ]
