# Generated by Django 5.2.16 on 2026-08-02 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
        ('pedidos', '0010_pedido_codigo_visivel_offline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorporacaoOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_idempotencia', models.UUIDField(unique=True)),
                ('entidade_local_id', models.UUIDField(unique=True)),
                ('estacao_id', models.UUIDField()),
                ('codigo_visivel', models.CharField(max_length=40, unique=True)),
                ('checksum', models.CharField(max_length=64)),
                ('incorporada_em', models.DateTimeField(auto_now_add=True)),
                ('pedido_global', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incorporacao_offline', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-incorporada_em'],
            },
        ),
        migrations.CreateModel(
            name='SequenciaOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacao_id', models.UUIDField()),
                ('codigo_origem', models.CharField(max_length=12)),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estacao_id', 'codigo_origem'), name='uniq_sequencia_offline_estacao_origem')],
            },
        ),
        migrations.CreateModel(
            name='UnidadeSincronizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave_idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entidade_local_id', models.UUIDField(unique=True)),
                ('estacao_id', models.UUIDField()),
                ('codigo_visivel', models.CharField(max_length=40)),
                ('sequencia_local', models.PositiveBigIntegerField()),
                ('versao_esquema', models.PositiveSmallIntegerField(default=1)),
                ('versao_politica', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('AGUARDANDO', 'Aguardando envio'), ('PREPARANDO', 'Preparando'), ('ENVIANDO', 'Enviando'), ('RECEBIDA', 'Recebida pela Central'), ('INCORPORADA', 'Incorporada'), ('FALHA_TEMPORARIA', 'Falha temporaria'), ('REQUER_ATENCAO', 'Requer atencao')], default='AGUARDANDO', max_length=32)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resultado', models.CharField(blank=True, max_length=120)),
                ('motivo_falha', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.operadorgestor')),
                ('pedido_local', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_sincronizacao', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['criada_em'],
                'indexes': [models.Index(fields=['estado', 'criada_em'], name='sincronizac_estado_0d07f4_idx'), models.Index(fields=['estacao_id', 'sequencia_local'], name='sincronizac_estacao_57e1da_idx')],
            },
        ),
    ]
