# Generated by Django 5.2.16 on 2026-08-02 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('segredo_hash', models.CharField(max_length=128)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
