# Generated by Django 5.2.15 on 2026-06-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone_principal', models.CharField(blank=True, max_length=32)),
                ('telefone_secundario', models.CharField(blank=True, max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx'), models.Index(fields=['telefone_principal'], name='clientes_cl_telefon_593e9a_idx')],
            },
        ),
    ]
