# Generated by Django 5.2.15 on 2026-06-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cpf_cnpj_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status_cadastro',
            field=models.CharField(choices=[('CADASTRADO', 'Cliente cadastrado'), ('NAO_CADASTRADO', 'Cliente nao cadastrado')], default='NAO_CADASTRADO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['status_cadastro', 'nome'], name='clientes_cl_status__c5a0e1_idx'),
        ),
    ]
