# Generated by Django 5.2.15 on 2026-06-25 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=16)),
                ('grupo', models.CharField(choices=[('VENDAS', 'Vendas'), ('SERVICOS', 'Servicos'), ('CUSTOS_FIXOS', 'Custos fixos'), ('CUSTOS_VARIAVEIS', 'Custos variaveis'), ('IMPOSTOS', 'Impostos'), ('RETIRADAS', 'Retiradas'), ('OUTROS', 'Outros')], default='OUTROS', max_length=32)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['tipo', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'grupo', 'ativa'], name='financeiro__tipo_b486be_idx')],
                'constraints': [models.UniqueConstraint(fields=('nome', 'tipo'), name='uniq_categoria_tipo')],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=16)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_competencia', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PREVISTO', max_length=16)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contafinanceira')),
                ('pagamento_pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamento_financeiro', to='pedidos.pagamentopedido')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-data_competencia', '-id'],
                'indexes': [models.Index(fields=['tipo', 'status', 'data_competencia'], name='financeiro__tipo_8116f0_idx'), models.Index(fields=['tipo', 'status', 'data_pagamento'], name='financeiro__tipo_1016d7_idx'), models.Index(fields=['categoria', 'data_competencia'], name='financeiro__categor_3966b6_idx'), models.Index(fields=['pedido'], name='financeiro__pedido__69ed30_idx')],
            },
        ),
    ]
