# Generated by Django 5.2.15 on 2026-06-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_produtoservico_prazo_entrega_dias_uteis'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVendasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_vendas', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'operador__nome'],
                'constraints': [models.UniqueConstraint(fields=('operador', 'ano', 'mes'), name='uniq_meta_vendas_operador_mes')],
            },
        ),
    ]
