# Generated by Django 5.2.15 on 2026-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_metavendasusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVendasGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes'), name='uniq_meta_vendas_geral_mes')],
            },
        ),
    ]
