# Generated by Django 5.2.15 on 2026-06-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True)),
                ('categoria', models.CharField(choices=[('PAINEL', 'Painel'), ('BOLSA', 'Bolsa'), ('GRAFICA_RAPIDA', 'Grafica rapida'), ('COMUNICACAO_VISUAL', 'Comunicacao visual'), ('OUTROS', 'Outros')], default='OUTROS', max_length=32)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('M2', 'Metro quadrado'), ('FOLHA', 'Folha'), ('SERVICO', 'Servico')], default='UN', max_length=16)),
                ('preco_venda_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('origem_legado', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['categoria', 'ativo'], name='catalogo_pr_categor_8d28f7_idx'), models.Index(fields=['nome'], name='catalogo_pr_nome_46962c_idx')],
            },
        ),
    ]
