# Generated by Django 5.2.15 on 2026-06-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoriaservico_produtoservico_categoria_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(default='global', max_length=64, unique=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferência de interface',
                'verbose_name_plural': 'Preferências de interface',
            },
        ),
    ]
