# Generated by Django 5.2.15 on 2026-06-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_operadorgestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(default='global', max_length=64, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=32)),
                ('telefone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='empresa/')),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil da empresa',
                'verbose_name_plural': 'Perfil da empresa',
            },
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='cargo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='foto',
            field=models.ImageField(blank=True, upload_to='usuarios/fotos/'),
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='papel',
            field=models.CharField(choices=[('ADMIN_GERAL', 'Administrador geral'), ('ADMIN', 'Administrador'), ('USUARIO', 'Usuario'), ('TEMPORARIO', 'Usuario temporario')], default='USUARIO', max_length=24),
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='telefone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
