# Generated by Django 5.2.15 on 2026-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_perfilempresa_operadorgestor_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadorgestor',
            name='senha',
            field=models.CharField(default='1234', max_length=128),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='instagram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='os_campos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='os_layout',
            field=models.CharField(choices=[('A5_DUPLICADO', 'A5 duplicada na A4'), ('A4_INTEIRA', 'A4 inteira')], default='A5_DUPLICADO', max_length=24),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
