# Generated by Django 5.2.15 on 2026-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_operadorgestor_senha_perfilempresa_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='os_cor_linhas',
            field=models.CharField(default='#a9bcff', max_length=7),
        ),
        migrations.AddField(
            model_name='perfilempresa',
            name='os_cor_textos',
            field=models.CharField(default='#06143d', max_length=7),
        ),
    ]
