# Generated by Django 5.2.15 on 2026-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_perfilempresa_os_linha_cabecalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_hash', models.CharField(max_length=64, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_por', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'verbose_name': 'Chave de recuperacao de senha',
                'verbose_name_plural': 'Chaves de recuperacao de senha',
                'ordering': ['-criada_em'],
            },
        ),
    ]
