# Generated by Django 5.2.15 on 2026-06-27 03:10

from django.db import migrations, models


def configurar_alertas_padrao(apps, schema_editor):
    CategoriaServico = apps.get_model("catalogo", "CategoriaServico")
    for categoria in CategoriaServico.objects.all():
        nome = (categoria.nome or "").lower()
        if "bolsa" in nome:
            categoria.alerta_dias_uteis = 7
        if "painel" in nome or "paine" in nome:
            categoria.alerta_mesmo_dia_apos_14h = True
        categoria.save(update_fields=["alerta_dias_uteis", "alerta_mesmo_dia_apos_14h"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_chaverecuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservico',
            name='alerta_dias_uteis',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='categoriaservico',
            name='alerta_mesmo_dia_apos_14h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriaservico',
            name='alerta_prazo_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(configurar_alertas_padrao, migrations.RunPython.noop),
    ]
