# Generated by Django 5.2.15 on 2026-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_categoriaservico_alerta_dias_uteis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='prazo_entrega_dias_uteis',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
