# Generated by Django 5.2.15 on 2026-06-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_produtoservico_prazo_entrega_dias_uteis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='operadorgestor',
            name='categoria_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='catalogo.categoriausuario'),
        ),
    ]
