# Generated by Django 5.2.15 on 2026-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_perfilempresa_contatos_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadorgestor',
            name='canal_atendimento_padrao',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online')], default='PRESENCIAL', max_length=16),
        ),
    ]
