# Generated by Django 5.2.16 on 2026-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_operadorgestor_canal_atendimento_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadorgestor',
            name='codigo_origem_offline',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
