# Generated by Django 5.2.16 on 2026-08-02 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0015_operadorgestor_canal_atendimento_padrao'),
        ('operacao', '0001_initial'),
        ('pedidos', '0009_pedido_estado_comercial_pedido_estado_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(blank=True, max_length=24)),
                ('criticidade', models.CharField(blank=True, max_length=24)),
                ('estado', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=16)),
                ('forma_encerramento', models.CharField(blank=True, choices=[('RESOLUCAO', 'Resolucao'), ('CANCELAMENTO_AUTORIZADO', 'Cancelamento autorizado'), ('INCORPORACAO_PROCESSO', 'Incorporacao a outro processo')], max_length=40)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='pendencias_destinatarias', to='catalogo.operadorgestor')),
                ('encerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_encerradas', to='catalogo.operadorgestor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias', to='pedidos.pedido')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias', to='operacao.processo')),
                ('responsavel_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_responsaveis', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-criada_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('encerrada_em__isnull', True)), fields=('processo', 'tipo'), name='pendencia_aberta_tipo_processo_unica')],
            },
        ),
    ]
