# Generated by Django 5.2.16 on 2026-08-10 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0017_perfilempresa_diretorio_artes_e_retencao'),
        ('missoes', '0004_mensagemchatmissao_notamissao_tarefamissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('FATO', 'Fato'), ('CORRELACAO', 'Correlação'), ('INFERENCIA', 'Inferência'), ('HIPOTESE', 'Hipótese')], max_length=16)),
                ('fonte', models.CharField(max_length=240)),
                ('referencia', models.CharField(blank=True, max_length=180)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('confianca', models.PositiveSmallIntegerField(default=100)),
                ('coletada_em', models.DateTimeField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_analiticas', to='catalogo.operadorgestor')),
            ],
            options={
                'ordering': ['-coletada_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=240)),
                ('resumo', models.TextField()),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('VALIDADA', 'Validada'), ('ARQUIVADA', 'Arquivada')], default='RASCUNHO', max_length=16)),
                ('confianca', models.PositiveSmallIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_criadas', to='catalogo.operadorgestor')),
                ('evidencias', models.ManyToManyField(blank=True, related_name='analises', to='analytics.evidenciaanalitica')),
            ],
            options={
                'ordering': ['-atualizada_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('objetivo', models.TextField()),
                ('premissas', models.JSONField(default=dict)),
                ('resultado', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('SALVA', 'Salva'), ('EXPIRADA', 'Expirada'), ('PROMOVIDA', 'Promovida para missão'), ('ARQUIVADA', 'Arquivada')], default='SALVA', max_length=16)),
                ('validade_ate', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulacoes_criadas', to='catalogo.operadorgestor')),
                ('missao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulacao_origem', to='missoes.missao')),
            ],
            options={
                'ordering': ['-atualizada_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='evidenciaanalitica',
            index=models.Index(fields=['tipo', 'coletada_em'], name='analytics_e_tipo_860b49_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacao',
            index=models.Index(fields=['estado', 'validade_ate'], name='analytics_s_estado_d98f9d_idx'),
        ),
    ]
