# Generated by Django 5.2.16 on 2026-08-02 14:10

import apps.arquivos.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0002_integridade_e_reconhecimento'),
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
        ('pedidos', '0011_artepedido_conteudo_sha256_artepedido_criado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(storage=apps.arquivos.models.ArmazenamentoAnexos(), upload_to=apps.arquivos.models.anexo_upload_to)),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desvinculado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_pedido_adicionados', to='catalogo.operadorgestor')),
                ('desvinculado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos_pedido_desvinculados', to='catalogo.operadorgestor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['criado_em', 'nome_original'],
                'indexes': [models.Index(fields=['pedido', 'desvinculado_em'], name='arquivos_an_pedido__1bd11b_idx'), models.Index(fields=['pedido', 'conteudo_sha256'], name='arquivos_an_pedido__88bb83_idx')],
            },
        ),
    ]
