# Generated by Django 5.2.16 on 2026-08-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0003_anexopedido'),
        ('catalogo', '0016_operadorgestor_codigo_origem_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivooficialarte',
            name='backup_previo_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivooficialarte',
            name='encerrado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivooficialarte',
            name='encerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_arquivo_oficial_encerrados', to='catalogo.operadorgestor'),
        ),
        migrations.AddField(
            model_name='arquivooficialarte',
            name='encerramento_observacao',
            field=models.TextField(blank=True),
        ),
    ]
